export const fruitBox = {
  a: "apple",
  b: "banana",
  c: "coconut",
  d: "dog",
  e: "elephant",
  f: "fish",
  g: "grapes",
  h: "house",
  i: "ice-cream",
  j: "jug",
  k: "kiwi",
  l: "lemon",
  m: "mango",
  n: "nest",
  o: "orange",
  p: "pineapple",
  q: "queen",
  r: "rose",
  s: "strawberry",
  t: "tomato",
  u: "umbrella",
  v: "van",
  w: "watermelon"
};
